apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-vite-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-vite-app
  template:
    metadata:
      labels:
        app: react-vite-app
    spec:
      containers:
        - name: react-vite-app
          image: quay.io/armada009/rental-car-web:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: react-vite-service
spec:
  selector:
    app: react-vite-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   name: react-vite-route
# spec:
#   to:
#     kind: Service
#     name: react-vite-service
#   port:
#     targetPort: 80
#   tls:
#     termination: edge
