apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .APP_NAME }}
  namespace: {{ .OCP_PROJECT }}
  labels:
    app: {{ .APP_NAME }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .APP_NAME }}
  template:
    metadata:
      labels:
        app: {{ .APP_NAME }}
    spec:
      containers:
        - name: {{ .APP_NAME }}
          image: "{{ .OCP_REGISTRY }}/{{ .OCP_PROJECT }}/{{ .APP_NAME }}:{{ .APP_FULL_VERSION }}"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: {{ .APP_NAME }}-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          imagePullPolicy: Always
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .APP_NAME }}-service
spec:
  selector:
    app: {{ .APP_NAME }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
